//! SeedVR2 adaptive window attention — the token-grid partition, as pure
//! integer/float math with zero MLX. Transcribed from ByteDance-Seed/SeedVR
//! `models/dit_v2/window.py` (Apache-2.0); full spec + trap list in
//! `docs/seedvr2-arch.md` §2.
//!
//! This is the paper's contribution and the piece most likely to be subtly
//! wrong, so it lives alone, hermetic and oracle-pinned: every test below
//! carries values generated by RUNNING the reference `window.py`, not by
//! re-deriving it from the same reading that produced the port. A partition
//! that is wrong in a way both the port and its test share is exactly the
//! failure this split is here to prevent.
//!
//! THE ADAPTIVE RULE, because it reads backwards: window SIZE is computed on
//! the 720p-equivalent grid (45x80 tokens) and window COUNT is then taken over
//! the ACTUAL grid. Window size is therefore constant across resolutions and
//! the number of windows grows — the opposite of a fixed-count split, and a
//! port that inverts it still runs and still produces an image.

const std = @import("std");

/// One window: half-open `[start, stop)` on each of the three token axes.
pub const Window = struct {
    t0: u32,
    t1: u32,
    h0: u32,
    h1: u32,
    w0: u32,
    w1: u32,

    pub fn tokenCount(self: Window) u32 {
        return (self.t1 - self.t0) * (self.h1 - self.h0) * (self.w1 - self.w0);
    }

    /// The window's own `(t, h, w)` extent. RoPE is applied window-LOCALLY —
    /// every window restarts at position `(txt_len, 0, 0)` — so this extent,
    /// not the window's offset in the full grid, is what the rope tables read.
    pub fn extent(self: Window) [3]u32 {
        return .{ self.t1 - self.t0, self.h1 - self.h0, self.w1 - self.w0 };
    }
};

/// Which of the two window layouts a layer uses. SeedVR2 alternates them:
/// EVEN layers `.plain`, ODD layers `.shifted`.
pub const Method = enum { plain, shifted };

/// `window_method[i]` for layer `i` under the 3B config's
/// `num_layers // 2 * ["720pwin_by_size_bysize", "720pswin_by_size_bysize"]`.
pub fn methodForLayer(layer: usize) Method {
    return if (layer % 2 == 0) .plain else .shifted;
}

/// 720p in DiT tokens: 720/8 (VAE) /2 (patch) = 45, 1280/8/2 = 80. The window
/// SIZE is derived on this grid no matter what the real grid is.
const REF_H: f64 = 45;
const REF_W: f64 = 80;

/// The reference caps the temporal window basis at 30 frames before dividing.
const T_CAP: u32 = 30;

fn ceilDiv(a: u32, b: u32) u32 {
    std.debug.assert(b > 0);
    return (a + b - 1) / b;
}

/// Window size in tokens for a `(t, h, w)` token grid under `num_windows`.
/// Separated from `partition` because it is the single step where the 720p
/// normalisation happens, and it is worth being able to assert on it directly.
pub fn windowSize(size: [3]u32, num_windows: [3]u32) [3]u32 {
    const t = size[0];
    const h: f64 = @floatFromInt(size[1]);
    const w: f64 = @floatFromInt(size[2]);

    // scale = sqrt((45*80) / (h*w)); resized = round(actual * scale).
    const scale = @sqrt((REF_H * REF_W) / (h * w));
    const resized_h: u32 = @intFromFloat(@round(h * scale));
    const resized_w: u32 = @intFromFloat(@round(w * scale));

    return .{
        ceilDiv(@min(t, T_CAP), num_windows[0]),
        ceilDiv(resized_h, num_windows[1]),
        ceilDiv(resized_w, num_windows[2]),
    };
}

/// Partition a token grid into attention windows. Caller owns the returned
/// slice.
///
/// EMISSION ORDER IS LOAD-BEARING: `for iw { for ih { for it } } }` — w-major,
/// t fastest. The flattened window sequence, every per-window cumulative
/// length, and the gather/scatter index vectors all inherit this order, so a
/// port that emits t-major is wrong everywhere at once and looks right in a
/// per-window unit test.
pub fn partition(
    allocator: std.mem.Allocator,
    size: [3]u32,
    num_windows: [3]u32,
    method: Method,
) ![]Window {
    const t = size[0];
    const h = size[1];
    const w = size[2];
    const ws = windowSize(size, num_windows);

    // Shift is half a window, and ONLY on axes where the window is actually
    // smaller than the extent — a shift on a single-window axis would emit a
    // leading empty window and a trailing partial one.
    const shift_t = method == .shifted and ws[0] < t;
    const shift_h = method == .shifted and ws[1] < h;
    const shift_w = method == .shifted and ws[2] < w;

    const nt = axisCount(t, ws[0], shift_t);
    const nh = axisCount(h, ws[1], shift_h);
    const nw = axisCount(w, ws[2], shift_w);

    var out: std.ArrayList(Window) = .empty;
    errdefer out.deinit(allocator);

    var iw: u32 = 0;
    while (iw < nw) : (iw += 1) {
        const sw = axisSpan(iw, w, ws[2], shift_w);
        if (sw[1] <= sw[0]) continue;
        var ih: u32 = 0;
        while (ih < nh) : (ih += 1) {
            const sh = axisSpan(ih, h, ws[1], shift_h);
            if (sh[1] <= sh[0]) continue;
            var it: u32 = 0;
            while (it < nt) : (it += 1) {
                const st = axisSpan(it, t, ws[0], shift_t);
                if (st[1] <= st[0]) continue;
                try out.append(allocator, .{
                    .t0 = st[0], .t1 = st[1],
                    .h0 = sh[0], .h1 = sh[1],
                    .w0 = sw[0], .w1 = sw[1],
                });
            }
        }
    }
    return out.toOwnedSlice(allocator);
}

/// Number of window slots on one axis before empties are dropped.
fn axisCount(extent: u32, win: u32, shifted: bool) u32 {
    if (!shifted) return ceilDiv(extent, win);
    // Reference: ceil((extent - 0.5) / win) + 1. The 0.5 never changes the
    // ceiling for integer extents unless extent is an exact multiple, so it
    // is computed in float to match exactly rather than reasoned away.
    const e: f64 = @floatFromInt(extent);
    const wf: f64 = @floatFromInt(win);
    const n: u32 = @intFromFloat(@ceil((e - 0.5) / wf));
    return n + 1;
}

/// `[start, stop)` for window `i` on one axis.
///
/// The shifted form truncates toward zero (`int()`), it does NOT round — a
/// half-window shift on an odd window size lands the boundary a token earlier
/// than rounding would, and every window after it inherits the offset.
fn axisSpan(i: u32, extent: u32, win: u32, shifted: bool) [2]u32 {
    if (!shifted) {
        const start = i * win;
        return .{ start, @min(start + win, extent) };
    }
    const fi: f64 = @floatFromInt(i);
    const wf: f64 = @floatFromInt(win);
    const raw_start = (fi - 0.5) * wf;
    const raw_stop = (fi - 0.5 + 1.0) * wf;
    const start: u32 = if (raw_start <= 0) 0 else @intFromFloat(@trunc(raw_start));
    const stop_i: i64 = @intFromFloat(@trunc(raw_stop));
    const stop: u32 = if (stop_i <= 0) 0 else @min(@as(u32, @intCast(stop_i)), extent);
    return .{ start, stop };
}

/// Total video tokens across all windows. Equals the grid's token count for
/// `.plain` (an exact tiling) but is LARGER for `.shifted`, whose clamped
/// edge windows overlap. Callers sizing buffers must use this, never `t*h*w`.
pub fn totalTokens(windows: []const Window) u64 {
    var n: u64 = 0;
    for (windows) |win| n += win.tokenCount();
    return n;
}

// ════════════════════════════════════════════════════════════════════════
// Tests. Every expectation below was produced by RUNNING the reference
// `models/dit_v2/window.py` at num_windows (4,3,3) — the 3B config — and is
// pasted verbatim. Do not "fix" one of these to match the port.
// ════════════════════════════════════════════════════════════════════════

const testing = std.testing;
const NW: [3]u32 = .{ 4, 3, 3 };

fn expectWindows(size: [3]u32, method: Method, expected: []const [6]u32) !void {
    const got = try partition(testing.allocator, size, NW, method);
    defer testing.allocator.free(got);
    testing.expectEqual(expected.len, got.len) catch |err| {
        std.debug.print("size {any} {s}: expected {d} windows, got {d}\n", .{
            size, @tagName(method), expected.len, got.len,
        });
        return err;
    };
    for (expected, got, 0..) |e, g, i| {
        const g6: [6]u32 = .{ g.t0, g.t1, g.h0, g.h1, g.w0, g.w1 };
        testing.expectEqual(e, g6) catch |err| {
            std.debug.print("size {any} {s} window {d}: expected {any}, got {any}\n", .{
                size, @tagName(method), i, e, g6,
            });
            return err;
        };
    }
}

test "window size comes from the 720p grid, not the real grid" {
    // The whole adaptive rule in one assertion: 720p and 1080p token grids
    // produce the SAME window size. If this ever reads (15,27) vs something
    // proportional to the input, the normalisation was dropped.
    try testing.expectEqual([3]u32{ 1, 15, 27 }, windowSize(.{ 1, 45, 80 }, NW));
    try testing.expectEqual([3]u32{ 1, 15, 27 }, windowSize(.{ 1, 68, 120 }, NW));
    try testing.expectEqual([3]u32{ 1, 15, 27 }, windowSize(.{ 1, 90, 160 }, NW));
    // ...and the COUNT is what grows.
    const a = try partition(testing.allocator, .{ 1, 45, 80 }, NW, .plain);
    defer testing.allocator.free(a);
    const b = try partition(testing.allocator, .{ 1, 68, 120 }, NW, .plain);
    defer testing.allocator.free(b);
    try testing.expectEqual(@as(usize, 9), a.len); // 3x3
    try testing.expectEqual(@as(usize, 25), b.len); // 5x5, same window size
}

test "temporal window divides min(t,30), not t" {
    try testing.expectEqual(@as(u32, 1), windowSize(.{ 1, 45, 80 }, NW)[0]);
    try testing.expectEqual(@as(u32, 2), windowSize(.{ 5, 45, 80 }, NW)[0]);
    try testing.expectEqual(@as(u32, 3), windowSize(.{ 9, 45, 80 }, NW)[0]);
    // Past the 30-frame cap the window size stops growing.
    try testing.expectEqual(@as(u32, 8), windowSize(.{ 30, 45, 80 }, NW)[0]);
    try testing.expectEqual(@as(u32, 8), windowSize(.{ 120, 45, 80 }, NW)[0]);
}

test "oracle: 720p single frame, plain — 9 windows w-major" {
    // ORACLE (reference window.py, size (1,45,80), num_windows (4,3,3)).
    try expectWindows(.{ 1, 45, 80 }, .plain, &.{
        .{ 0, 1, 0, 15, 0, 27 },  .{ 0, 1, 15, 30, 0, 27 },  .{ 0, 1, 30, 45, 0, 27 },
        .{ 0, 1, 0, 15, 27, 54 }, .{ 0, 1, 15, 30, 27, 54 }, .{ 0, 1, 30, 45, 27, 54 },
        .{ 0, 1, 0, 15, 54, 80 }, .{ 0, 1, 15, 30, 54, 80 }, .{ 0, 1, 30, 45, 54, 80 },
    });
}

test "oracle: 720p single frame, shifted — 16 windows with clamped edges" {
    // ORACLE. Note the leading half-windows (0..7, 0..13) and the trailing
    // clamped ones — the shifted layout is NOT a tiling and its windows sum to
    // more than 45*80 tokens.
    try expectWindows(.{ 1, 45, 80 }, .shifted, &.{
        .{ 0, 1, 0, 7, 0, 13 },   .{ 0, 1, 7, 22, 0, 13 },   .{ 0, 1, 22, 37, 0, 13 },  .{ 0, 1, 37, 45, 0, 13 },
        .{ 0, 1, 0, 7, 13, 40 },  .{ 0, 1, 7, 22, 13, 40 },  .{ 0, 1, 22, 37, 13, 40 }, .{ 0, 1, 37, 45, 13, 40 },
        .{ 0, 1, 0, 7, 40, 67 },  .{ 0, 1, 7, 22, 40, 67 },  .{ 0, 1, 22, 37, 40, 67 }, .{ 0, 1, 37, 45, 40, 67 },
        .{ 0, 1, 0, 7, 67, 80 },  .{ 0, 1, 7, 22, 67, 80 },  .{ 0, 1, 22, 37, 67, 80 }, .{ 0, 1, 37, 45, 67, 80 },
    });
}

test "oracle: 1080p single frame keeps the 15x27 window and grows to 5x5" {
    const got = try partition(testing.allocator, .{ 1, 68, 120 }, NW, .plain);
    defer testing.allocator.free(got);
    try testing.expectEqual(@as(usize, 25), got.len);
    // ORACLE spot-checks: first three (t,h,w) triples and the last.
    try testing.expectEqual([6]u32{ 0, 1, 0, 15, 0, 27 }, .{ got[0].t0, got[0].t1, got[0].h0, got[0].h1, got[0].w0, got[0].w1 });
    try testing.expectEqual([6]u32{ 0, 1, 15, 30, 0, 27 }, .{ got[1].t0, got[1].t1, got[1].h0, got[1].h1, got[1].w0, got[1].w1 });
    try testing.expectEqual([6]u32{ 0, 1, 30, 45, 0, 27 }, .{ got[2].t0, got[2].t1, got[2].h0, got[2].h1, got[2].w0, got[2].w1 });
    // Edge windows clamp to the real grid, not to a multiple of the size.
    try testing.expectEqual([6]u32{ 0, 1, 60, 68, 108, 120 }, .{
        got[24].t0, got[24].t1, got[24].h0, got[24].h1, got[24].w0, got[24].w1,
    });
}

test "oracle: multi-frame plain partitions time w-major with t fastest" {
    // ORACLE (5,45,80) plain — 27 windows, wt=2 so t splits 0..2, 2..4, 4..5.
    // The first three windows differ only in t: that IS the emission order.
    const got = try partition(testing.allocator, .{ 5, 45, 80 }, NW, .plain);
    defer testing.allocator.free(got);
    try testing.expectEqual(@as(usize, 27), got.len);
    try testing.expectEqual([2]u32{ 0, 2 }, .{ got[0].t0, got[0].t1 });
    try testing.expectEqual([2]u32{ 2, 4 }, .{ got[1].t0, got[1].t1 });
    try testing.expectEqual([2]u32{ 4, 5 }, .{ got[2].t0, got[2].t1 });
    // ...and only then does h advance.
    try testing.expectEqual([2]u32{ 0, 2 }, .{ got[3].t0, got[3].t1 });
    try testing.expectEqual([2]u32{ 15, 30 }, .{ got[3].h0, got[3].h1 });
}

test "oracle: non-multiple grids clamp rather than pad" {
    // ORACLE (1,30,53) plain — 4 windows: h splits 15+15, w splits 27+26.
    try expectWindows(.{ 1, 30, 53 }, .plain, &.{
        .{ 0, 1, 0, 15, 0, 27 },  .{ 0, 1, 15, 30, 0, 27 },
        .{ 0, 1, 0, 15, 27, 53 }, .{ 0, 1, 15, 30, 27, 53 },
    });
}

test "oracle: a grid smaller than one window is a single window, shifted or not" {
    // ORACLE (1,17,17): scale pushes the 720p-equivalent above the real grid,
    // so window >= extent on every axis, the shift is suppressed, and both
    // methods collapse to one full-grid window. This is the case where a
    // shift-always implementation emits a bogus empty leading window.
    try expectWindows(.{ 1, 17, 17 }, .plain, &.{.{ 0, 1, 0, 17, 0, 17 }});
    try expectWindows(.{ 1, 17, 17 }, .shifted, &.{.{ 0, 1, 0, 17, 0, 17 }});
}

test "oracle: window counts across the full case matrix" {
    // ORACLE counts for every case in the generated matrix. A count mismatch
    // is the cheapest possible detector for an off-by-one in axisCount.
    const cases = [_]struct { size: [3]u32, plain: usize, shifted: usize }{
        .{ .size = .{ 1, 45, 80 }, .plain = 9, .shifted = 16 },
        .{ .size = .{ 1, 68, 120 }, .plain = 25, .shifted = 30 },
        .{ .size = .{ 5, 45, 80 }, .plain = 27, .shifted = 48 },
        .{ .size = .{ 1, 32, 32 }, .plain = 4, .shifted = 9 },
        .{ .size = .{ 1, 30, 53 }, .plain = 4, .shifted = 9 },
        .{ .size = .{ 9, 90, 160 }, .plain = 108, .shifted = 196 },
        .{ .size = .{ 1, 17, 17 }, .plain = 1, .shifted = 1 },
        .{ .size = .{ 3, 45, 80 }, .plain = 27, .shifted = 48 },
        // Second batch, dumped by tests/dump_seedvr2_fixtures.py against the
        // reference partitioner (tests/fixtures/seedvr2/windows.json).
        .{ .size = .{ 1, 90, 160 }, .plain = 36, .shifted = 49 },
        .{ .size = .{ 17, 45, 80 }, .plain = 36, .shifted = 64 },
        .{ .size = .{ 1, 135, 240 }, .plain = 81, .shifted = 100 },
        // t=33 exceeds the 30-frame cap, so wt = ceil(30/4) = 8, NOT ceil(33/4).
        // This is the only case in the matrix that exercises T_CAP; without it
        // a port that divides the real `t` passes everything else.
        .{ .size = .{ 33, 68, 120 }, .plain = 125, .shifted = 150 },
    };
    for (cases) |c| {
        const p = try partition(testing.allocator, c.size, NW, .plain);
        defer testing.allocator.free(p);
        const s = try partition(testing.allocator, c.size, NW, .shifted);
        defer testing.allocator.free(s);
        testing.expectEqual(c.plain, p.len) catch |err| {
            std.debug.print("plain {any}: want {d} got {d}\n", .{ c.size, c.plain, p.len });
            return err;
        };
        testing.expectEqual(c.shifted, s.len) catch |err| {
            std.debug.print("shifted {any}: want {d} got {d}\n", .{ c.size, c.shifted, s.len });
            return err;
        };
    }
}

test "plain windows exactly tile the grid; shifted windows overlap" {
    // INVARIANT, not an oracle value. The plain layout is a partition, so its
    // tokens sum to the grid. The shifted layout clamps its edge windows and
    // therefore covers some tokens twice — code that sizes a buffer at t*h*w
    // for the shifted pass overflows, which is why totalTokens exists.
    const sizes = [_][3]u32{ .{ 1, 45, 80 }, .{ 5, 45, 80 }, .{ 1, 68, 120 }, .{ 1, 30, 53 } };
    for (sizes) |size| {
        const grid: u64 = @as(u64, size[0]) * size[1] * size[2];
        const p = try partition(testing.allocator, size, NW, .plain);
        defer testing.allocator.free(p);
        try testing.expectEqual(grid, totalTokens(p));

        const s = try partition(testing.allocator, size, NW, .shifted);
        defer testing.allocator.free(s);
        try testing.expect(totalTokens(s) >= grid);
    }
}

test "plain windows are disjoint and cover every token exactly once" {
    // INVARIANT. totalTokens matching the grid is necessary but not
    // sufficient — a partition could double-cover one token and miss another
    // and still sum correctly. Mark the grid.
    const size: [3]u32 = .{ 5, 45, 80 };
    const n: usize = size[0] * size[1] * size[2];
    const seen = try testing.allocator.alloc(u8, n);
    defer testing.allocator.free(seen);
    @memset(seen, 0);

    const wins = try partition(testing.allocator, size, NW, .plain);
    defer testing.allocator.free(wins);
    for (wins) |win| {
        var t = win.t0;
        while (t < win.t1) : (t += 1) {
            var h = win.h0;
            while (h < win.h1) : (h += 1) {
                var w = win.w0;
                while (w < win.w1) : (w += 1) {
                    seen[(t * size[1] + h) * size[2] + w] += 1;
                }
            }
        }
    }
    for (seen, 0..) |c, i| {
        testing.expectEqual(@as(u8, 1), c) catch |err| {
            std.debug.print("token {d} covered {d} times\n", .{ i, c });
            return err;
        };
    }
}

test "shifted windows cover every token at least once" {
    // INVARIANT. Overlap is expected; a HOLE is not — a token no window covers
    // would silently never be attended on odd layers.
    const size: [3]u32 = .{ 5, 45, 80 };
    const n: usize = size[0] * size[1] * size[2];
    const seen = try testing.allocator.alloc(u8, n);
    defer testing.allocator.free(seen);
    @memset(seen, 0);

    const wins = try partition(testing.allocator, size, NW, .shifted);
    defer testing.allocator.free(wins);
    for (wins) |win| {
        var t = win.t0;
        while (t < win.t1) : (t += 1) {
            var h = win.h0;
            while (h < win.h1) : (h += 1) {
                var w = win.w0;
                while (w < win.w1) : (w += 1) {
                    seen[(t * size[1] + h) * size[2] + w] +|= 1;
                }
            }
        }
    }
    for (seen, 0..) |c, i| {
        testing.expect(c >= 1) catch |err| {
            std.debug.print("token {d} never covered by any shifted window\n", .{i});
            return err;
        };
    }
}

test "methodForLayer alternates plain/shifted from layer 0" {
    // The 3B config is `num_layers // 2 * [plain, shifted]`, so layer 0 is
    // plain. Starting on shifted mis-pairs all 32 layers.
    try testing.expectEqual(Method.plain, methodForLayer(0));
    try testing.expectEqual(Method.shifted, methodForLayer(1));
    try testing.expectEqual(Method.plain, methodForLayer(30));
    try testing.expectEqual(Method.shifted, methodForLayer(31));
}

test "no window is empty or inverted at any size" {
    // Fuzz the guard that drops empty slices. An empty window would produce a
    // zero-length attention sequence and a division by zero in the softmax.
    var t: u32 = 1;
    while (t <= 9) : (t += 2) {
        var h: u32 = 8;
        while (h <= 96) : (h += 7) {
            var w: u32 = 8;
            while (w <= 160) : (w += 11) {
                for ([_]Method{ .plain, .shifted }) |m| {
                    const wins = try partition(testing.allocator, .{ t, h, w }, NW, m);
                    defer testing.allocator.free(wins);
                    try testing.expect(wins.len > 0);
                    for (wins) |win| {
                        try testing.expect(win.t1 > win.t0);
                        try testing.expect(win.h1 > win.h0);
                        try testing.expect(win.w1 > win.w0);
                        try testing.expect(win.t1 <= t);
                        try testing.expect(win.h1 <= h);
                        try testing.expect(win.w1 <= w);
                    }
                }
            }
        }
    }
}
